### ISSUE TITLE
【お願い】プラグインの解説ブログを復旧していただけないでしょうか？

### ISSUE THREAD

**Issue by takuma-competition** [crz33/vscode-wordpress-post#12]
・以下のブログをアクセスできるように復旧していただけないでしょうか？
[WordPressの記事投稿におすすめのVSCode拡張機能「WordPress Post」の使い方](https://masa86.net/blog-wordpress-post/)

・当方、こちらのプラグインの開発者様と上記ブログの記載者は同一の方であると予想しております。（間違っていたらすみません。）
・プログラム本体に関わることではないので、issueに記載するのは不適切かと思いましたが、連絡手段が思いつかずissueに投稿させていただきました。
・お忙しいところ恐縮ですが、ご返信いただけると幸いです。

**Comment by crz33** [comment]
すみませんでした。しばらくメンテナンスしてない間にサーバの契約が切れてました。
このツール使ってたおかげで記事は復旧できました。

**Comment by takuma-competition** [comment]
【お礼】ご対応ありがとうございました。
お忙しいところご対応いただき大変ありがとうございます。
私も個人ブログを運営しているのですが、[vscode-wordpress-post](https://github.com/crz33/vscode-wordpress-post)を活用させていただいております。
誠に勝手なお願いで恐縮ですが、引き続き上記プラグイン保守、運用を続けていただけると大変助かります。

合わせて、こちらのツール開発していただきありがとうございました。
また、わからない点等ありましたら、質問させていただけると幸いです。
